services:
  saga_orchestrator:
    build: .
    container_name: saga_orchestrator 
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5123:5123"
    networks:
      - labo05-network
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    #ports:
    #  - "16686:16686"      # Jaeger UI
    #  - "14268:14268"      # Jaeger collector HTTP
    #  - "14250:14250"      # Jaeger collector gRPC (legacy)
    #  - "4317:4317"        # OTLP gRPC receiver
    #  - "4318:4318"        # OTLP HTTP receiver
    #  - "6831:6831/udp"    # Jaeger agent (legacy)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - labo05-network

networks:
  labo05-network:
    external: true

volumes:
  mysql_data:
  prometheus_data:
