services:
  saga_orchestrator:
    build: .
    container_name: saga_orchestrator 
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5123:5123"
    networks:
      - labo06-network

networks:
  labo06-network:
    external: true

volumes:
  mysql_data:
  prometheus_data:
